---
# nginx_ppa_repo
# - repo: "nginx/stable"                         #required
#   state: present                               #default
#   update_cache: yes                            #default
#   validate_certs: yes                          #default
nginx_ppa_repo:
- repo: "nginx/stable"
nginx_user: "www-data"
nginx_create_servers: true
nginx_disable_default_server: true
nginx_access_log: "/var/log/nginx/access.log main"
nginx_client_max_body_size: "64m"
nginx_default_type: "application/octet-stream"
nginx_error_log: "/var/log/nginx/error.log warn"
nginx_gzip: "on"
nginx_gzip_comp_level: "5"
nginx_gzip_disable: "msie6"
nginx_gzip_min_length: "256"
nginx_gzip_proxied: "any"
nginx_gzip_vary: "on"
nginx_gzip_types:
- "application/atom+xml"
- "application/javascript"
- "application/json"
- "application/rss+xml"
- "application/vnd.ms-fontobject"
- "application/x-font-ttf"
- "application/x-web-app-manifest+json"
- "application/xhtml+xml"
- "application/xml"
- "font/opentype"
- "image/svg+xml"
- "image/x-icon"
- "text/css"
- "text/plain"
- "text/x-component"
nginx_keepalive_timeout: "20"
nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_server_tokens: "off"
nginx_worker_processes: "1"
nginx_worker_connections: "8000"
nginx_worker_rlimit_nofile: "8192"
# nginx_server_configs
nginx_server_configs: []
# see: templates/server.conf.j2
#- name: "local"                                 #required
#  servers:
#  - listen: ["80 default_server"]               #required
#    return: "444"
#  - listen: ["80"]                              #required
#    server_name: "www.local.dev"
#    return: "301 $scheme://local.dev$request_uri"
#  - listen: ["80"]                              #required
#    server_name: "local.dev"
#    root: "/var/www/html"
#    index: "index.html index.htm"
#    charset: "utf-8"
#    access_log: "/var/log/nginx/local.log"
#    error_log: "/var/log/nginx/local-error.log error"
#    #ssl: "on"
#    #ssl_certificate: "/srv/ssl/certs/local.crt"
#    #ssl_certificate_key: "/srv/ssl/private/local.key"
#    #log_not_found: "on"
#    #merge_slashes: "on"
#    #disable_symlinks: "off"
#    #etag: "on"
#    #chunked_transfer_encoding: "on"
#    #client_max_body_size: "64m"
#    #default_type: "application/octet-stream"
#    #error_pages: ["404 /404.html"]
#    includes: ["h5bp/basic.conf"]
#    locations:
#    - match: "= /favicon.ico"
#      access_log: "off"
#      log_not_found: "off"
#    - match: "= /robots.txt"
#      access_log: "off"
#      log_not_found: "off"
#    - match: "/"
#      try_files: "$uri $uri/ =404"
