---
- name: "pip installed"
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - "python"
  - "python-dev"
  - "python-pip"
  - "build-essential"

- name: "libsass installed"
  become: yes
  pip:
    name: "libsass"
    state: "{% if libsass_keep_updated %}latest{% else %}present{% endif %}"
